name: 'Auto Assign'
on:
  pull_request_target:
    types: [opened, ready_for_review, reopened]

jobs:
  add-reviews:
    if: ${{ join(github.event.pull_request.requested_reviewers.*.login, ',') == '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.4
        with:
          configuration-path: ".github/pr-auto-assign-config.yml"
